# Generated by Django 3.1.7 on 2022-06-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220623_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_pin',
            field=models.IntegerField(),
        ),
    ]
